version: 2.1

orbs:
  docker: circleci/docker@1.2.1
  gcp-gke: circleci/gcp-gke@1.1.0
  gcp-gcr: circleci/gcp-gcr@0.12.0

jobs:
  flow-deploy:
    docker:
      - image: debian:latest
    description: Deploy smart contracts to the proper network
    parameters:
      stuff:
        description:
          some stuff
        type: string
    steps:
      - checkout
      - setup_remote_docker
      - run: apt update && apt upgrade
      - run: apt -y install curl
      - run: sh -ci "$(curl -fsSL https://storage.googleapis.com/flow-cli/install.sh)"
      - run: ls -l /root/.local/bin
      - run: /root/.local/bin/flow version
      - run: ./cli-cicd update-nft-contract
      - run: ./cli-cicd update-single-contract
      - run: ./cli-cicd update-market-contract
      # rest of cli commands go here via /root/.local/bin/flow {command}

  deploy:
    description: Deploy application to Google Kubernetes Engine
    machine: true
    parameters:
      cluster:
        description: |
          Name of gke cluster
        type: string
      container:
        description: |
          Name of docker container with organization
        type: string
      deployment:
        description: |
          Name of k8 deployment
        type: string
      image:
        description: |
          Name of docker image with organization
        type: string
      tag:
        description: |
          Docker image tag
        type: string
      namespace:
        description: |
          K8 namespace
        type: string
    steps:
      - gcp-gke/install
      - gcp-gke/update-kubeconfig-with-credentials:
          cluster: << parameters.cluster >>
          perform-login: true
      - gcp-gke/rollout-image:
          cluster: << parameters.cluster >>
          container: << parameters.container >>
          deployment: << parameters.deployment >>
          image: << parameters.image >>
          tag: << parameters.tag >>
          namespace: << parameters.namespace >>
  test:
    description: Run integration tests after deployment is finished
    docker:
      - image: circleci/golang:latest
    parameters:
      environment:
        description: |
          The environment to test
        type: string
    steps:
      - checkout
      - run: make test-<< parameters.environment >>

workflows:
  docker-build-push-deploy-dev:
    jobs:
      - flow-deploy:
          stuff: stuff
          filters:
            branches:
              only:
                - dev
      - gcp-gcr/build-and-push-image:
          image: na-cadence
          tag: 0.0.2
          registry-url: gcr.io
          filters:
            branches:
              only:
                - dev
      - deploy:
          cluster: pw-dev
          container: na-cadence
          deployment: na-cadence
          image: gcr.io/pineappleworkshop/na-cadence
          tag: 0.0.2
          namespace: default
          filters:
             branches:
               only:
                 - dev
          requires:
            - gcp-gcr/build-and-push-image
      - test:
          environment: dev
          filters:
            branches:
              only:
                - dev
          requires:
            - deploy

  docker-build-push-deploy-stage:
    jobs:
#      - flow-deploy:
#          stuff: stuff
#          filters:
#            branches:
#              only:
#                - dev
      - deploy:
          cluster: pw-prod
          container: na-cadence
          deployment: na-cadence
          image: gcr.io/pineappleworkshop/na-cadence
          tag: 0.0.2
          namespace: na
          filters:
            branches:
              only:
                - stage
      - test:
          environment: stage
          filters:
            branches:
              only:
                - stage
          requires:
            - deploy
