apiVersion: v1
kind: Service
metadata:
  labels:
    app: na-cadence
  name: na-cadence
  namespace: na
spec:
  ports:
    - port: 3444
      targetPort: 3444
      protocol: TCP
  selector:
    app: na-cadence
