package handlers

const (
	CADENCE_FILE_PATH_TEST        = "../cadence"
	CADENCE_FILE_PATH_WORKSTATION = "./cadence"
	CADENCE_FILE_PATH_CLUSTER     = "/go/bin/cadence"

	SERVICE_ACCOUNT_ADDRESS             = "SERVICE_ACCOUNT_ADDRESS"
	FUSD_CONTRACT_ADDRESS               = "FUSD_CONTRACT_ADDRESS"
	NON_FUNGIBLE_TOKEN_CONTRACT_ADDRESS = "NON_FUNGIBLE_TOKEN_CONTRACT_ADDRESS"
	FUNGIBLE_TOKEN_CONTRACT_ADDRESS     = "FUNGIBLE_TOKEN_CONTRACT_ADDRESS"

	FILE_TYPE_TRANSACTION = "transaction"
	FILE_TYPE_SCRIPT      = "script"
)
